# [CIT-UNA] CURSO BASICO DE INTRODUCCION A BIG DATA
#
# "Aquí hay algunos ejemplos de variables que se pueden configurar::
#
# PRODUCTION_SERVER = hercules
# TEST_SERVER = zeus
# DEVELOPMENT_SERVER = thor
#
# Uso en PDI: Para llamar a estas variables dentro de Spoon, utiliza la sintaxis ${VARIABLE} o %%VARIABLE%%.
#
# Nota: las líneas como estas, con un # al inicio, son comentarios.
#

# Ajustes de Memoria y Performance
KETTLE_MAX_LOG_SIZE_IN_LINES = 5000

# Configuración de Rutas
CIT_INPUT_HOME=D:\\Storage\\Opendata\\SFP\\Funcionarios_2026
CIT_OUTPUT_HOME=D:\\Dataset\\Output

# Archivos CSV
CIT_FILENAME_EDA=${CIT_INPUT_HOME}\\funcionarios_2026_1.csv
CIT_WSL_FILENAME_EDA=\\\\wsl.localhost\\Ubuntu\\opt\\repo\\cit-bigdata-lab\\data\\staged\\sfp_funcionarios\\2026_01\\funcionarios_2026_1_utf8.csv
CIT_WSL_FILENAME_EDA_SAMPLE=\\\\wsl.localhost\\Ubuntu\\opt\\repo\\cit-bigdata-lab\\data\\exported\\funcionarios_2026_1_sample100k.csv

# DuckDB
CIT_DUCKDB_HOME=\\\\wsl.localhost\\Ubuntu\\opt\\repo\\cit-bigdata-lab\\data\\duckdb
CIT_DUCKDB_EDA_CONNECTION_URL=jdbc:duckdb:${CIT_DUCKDB_HOME}\\eda.duckdb

# MotherDuck
CIT_MOTHERDUCK_TOKEN_ID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJqaW1lbmV6QHBvbC51bmEucHkiLCJtZFJlZ2lvbiI6ImF3cy11cy1lYXN0LTEiLCJzZXNzaW9uIjoicmppbWVuZXoucG9sLnVuYS5weSIsInBhdCI6IndweFFwVXF1allDNzdGTVJQU1NmcHZrU1Z0bEMweDc3cnFUNmV2QkpJT2siLCJ1c2VySWQiOiJlZTJiYTAzNi1lZmExLTRlODgtOTc2NC1jY2VkNjc4OTliYzAiLCJpc3MiOiJtZF9wYXQiLCJyZWFkT25seSI6ZmFsc2UsInRva2VuVHlwZSI6InJlYWRfd3JpdGUiLCJpYXQiOjE3NzYxMDk4ODh9.ZzN4MvpgQrs9ZJglgnvf95rw-Jggr_voioH4Rd40NcM
CIT_MOTHERDUCK_EDA_CONNECTION_URL=jdbc:duckdb:md:eda?motherduck_token=${CIT_MOTHERDUCK_TOKEN_ID}
